extends:
  eslint-config-airbnb

parser:
  babel-eslint

settings:
  import/resolver:
    webpack:
      config: 'webpack.config.js'

plugins:
  - import
  - filenames
  - react

ecmaFeatures:
  jsx: true
  modules: true
  destructuring: true
  classes: true
  arrowFunctions: true

env:
  browser: true

rules:
  indent: 2
  global-require: 0
  comma-dangle: 0
  consistent-return: 1
  class-methods-use-this: 1
  import/no-unresolved: 0
  import/extensions:
    - error
    - never
    - { "less": "always" }
  filenames/match-regex:
    - 2
    - "([A-Za-z][a-z0-9]+)([A-Z][a-z0-9]+)*"
    - true
  filenames/match-exported: 2
  filenames/no-index: 0
  no-restricted-syntax:
    - error
    - {
        "selector": "ForStatement",
        "message": "For expressions are not allowed."
      }
  react/jsx-filename-extension:
    - error
    - { "extensions": [".js", ".jsx"] }
  react/prop-types: 0
  react/prefer-stateless-function: 1
  react/jsx-boolean-value: 0
  import/no-extraneous-dependencies: 0
